### PR TITLE
Support storages other than GCS

### PR DESCRIPTION
**Pull request by ranlu**
Use s5cmd for storage with a S3 interface, otherwise try with cloudfiles. Right now there is no way to update alias for cloudfiles, so only the official alias: matrix and tigerdata are supported

### CODE REVIEW

**Comment by william-silversmith** [comment]
Hi Ran,

It's possible to dynamically update the aliases. Lmk if you're interested
in learning more.

Will

**Comment by ranlu** [comment]
You mean using `cloudfiles alias`? Or there are cloudfiles functions to call?

**Comment by ranlu** [comment]
There are several issues with cloudvolume/cloudfiles. cloudvolume does not support `s3://https://` type of addresses, so I am forced to use alias. and cloudfiles alias returns an error when `~/.cloudfiles` does not exist, create alias is logically the first thing one want to do if we try to setup a new docker container, so it is quite annoying

**Comment by william-silversmith** [comment]
There are functions in cloudfiles.paths

https://github.com/seung-lab/cloud-files/blob/35acfcfbecc6910c9e52fbe40a931d550e96e4f6/cloudfiles/paths.py#L77

**Comment by william-silversmith** [comment]
Sounds like I should fix CV to support s3://http:// I'm seeing this
complaint from multiple people

**Comment by ranlu** [comment]
I tried add_alias, this is seems to be dynamic, I mean it does not create an alias file so the alias only works for this particular session, correct? I would prefer a permanent setup. I could allow the user to upload a alias files directly I suppose. Still quite ugly. 
BTW, Have you considered adding a "globlal" location for cloudfiles/cloudvolume configs, like `/etc/cloudvolume`?  right now everything goes to $HOME (or directly in `/` which is ugly as hell), but it is no reliable method to find out $HOME of a unknown docker image without actually running it. This makes it harder to setup a container, no idea where to put the config files before the container runs

**Comment by william-silversmith** [comment]
Yes, that's right it's process specific.

It sounds like a CV update is the best approach here but I'll think about
adding a persistent add alias function.

You make a good point about CV configuration. Maybe I should add an
environment variable for CV that would use an alternative location?

**Comment by ranlu** [comment]
Sure, a environment variable like `CLOUDVOLUME_HOME` is a good solution. A somewhat related issue is to unify config location for cloudvolume and cloudfiles, For historical reason I send secrets to `~/.cloudvolume/secrets`, but I suppose alias files has to be in `~/.cloudfiles`. Do you recommend/plan to gradually move everything to `~/.cloudfiles`?

**Comment by william-silversmith** [comment]
Sounds good. I'll see if I can do that environment variable update and path
correction Monday/Tuesday.

Regarding the best location, CloudFiles is the primary network backend
right now but CV is logically a separate entity. Right now I plan on
supporting both methods indefinitely, though I could perhaps be convinced
otherwise.

**Comment by ranlu** [comment]
Thanks, my plan is to eventually move the secrets to `~/.cloudfiles` as well. Like you said, cloudfiles is the network backend, so logically the credential and alias should be managed by it. Actually I guess the reason `s3://http://` does not work in cloudvolume is because it does its own checks in its own paths.py. These functions logically should be merged to cloudfiles. `~/cloudvolume` can store things that are more specific to "volume", like caching I suppose.

**Comment by william-silversmith** [comment]
The merging is partially done, but CV needs to handle format specs like
"precomputed://" or "graphene://" or "n5://" while these are meaningless to
cloud files, so I think there will always be a path check in CV and CF
unfortunately, but it can be better disentangled perhaps.

**Comment by ranlu** [comment]
Hmm, I use `cloudfiles.paths.extract` to parse alias already, did not realize it does not work with `precomputed://tigerdata://`. Should I use `cloudvolume.path.extract` after you make it support urls like `s3://https://`? The reason I need this is to use s5cmd to upload files that are too large for cloudfiles. But all the s3 tools only allow standard `s3://` path.

**Comment by william-silversmith** [comment]
I'll need to get back to you on that. CV tools are best for CV paths (once
that feature is added) though I'm not sure if they'll handle aliases as
well.

I really should add that multipart upload support...

**Comment by ranlu** [comment]
Great. I will merge this pr

**Pull request merged**
